version: "3.7"

services:
  base-api:
    hostname: base-api
    container_name: base-api
    volumes:
      - .:/app
    ports:
      - 8080:8080
    image: clearlinux/node:latest
    working_dir: /app
    command: sh docker/develop/dev.sh
    networks:
      - base-api-net

networks:
  base-api-net:
    driver: bridge
