version: "3.7"

services:
  base-api:
    hostname: base-api
    container_name: base-api
    volumes:
      - .:/app
    ports:
      - 8080:8080
    image: clearlinux/node:latest
    working_dir: /app
    command: sh docker/develop/dev.sh
    networks:
      - base-api-net

  base-api-mysql:
    image: mysql:8.0.29
    container_name: base-api-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=base-api
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - base-api-net

networks:
  base-api-net:
    driver: bridge